spring:

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test-db
    username: sa
    password:

  batch:
#     job:
#       enabled: false

     jdbc:
       initialize-schema: always

  h2:
    console:
      enabled: true
      path: /h2-console